version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER registry.cn-beijing.aliyuncs.com --password-stdin
      - run: make docker
      - run: docker images

  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER registry.cn-beijing.aliyuncs.com --password-stdin
      - run: make docker-push
      - run: docker images

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters: # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /^v(\d+)\.(\d+)\.(\d+)/
            branches:
              ignore: /.*/
